spring:
  application:
    name: Logging

server:
  port: 9191

management:
  endpoints:
    web:
      exposure:
        include: "health,info,loggers"

#logging:
#  level:
#    com:
#      demo:
#        Logging:
#          controller: DEBUG

#logging:
#  level:
#    root: OFF

